/**
 * cashfreeService — loads the Cashfree SDK and requests a backend-generated payment session id.
 */

const getEnvVar = (key) => {
  const value = import.meta.env[key];
  return value || '';
};

export const CASHFREE_APP_ID = getEnvVar('VITE_CASHFREE_APP_ID');
export const CASHFREE_ENV = getEnvVar('VITE_CASHFREE_ENV') || 'sandbox';
const CASHFREE_PAYMENT_SESSION_ENDPOINT = '/api/cashfree/session';

const CASHFREE_SCRIPT_URL = 'https://sdk.cashfree.com/js/checkout.js';

export function loadCashfreeScript() {
  return new Promise((resolve) => {
    if (window.Cashfree) return resolve(true);

    const script = document.createElement('script');
    script.src = CASHFREE_SCRIPT_URL;
    script.async = true;
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });
}

export async function createCashfreePaymentSession({
  orderId,
  amount,
  customerName,
  customerEmail,
  customerPhone,
  orderNote,
}) {
  if (!CASHFREE_APP_ID) {
    throw new Error('Cashfree app ID is not configured. Please set VITE_CASHFREE_APP_ID.');
  }

  const response = await fetch(CASHFREE_PAYMENT_SESSION_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      orderId,
      amount,
      currency: 'INR',
      customerName,
      customerEmail,
      customerPhone,
      orderNote,
      appId: CASHFREE_APP_ID,
      mode: CASHFREE_ENV,
    }),
  });

  if (!response.ok) {
    const text = await response.text().catch(() => '');
    throw new Error(text || 'Unable to create Cashfree payment session.');
  }

  const data = await response.json().catch(() => ({}));

  if (!data?.paymentSessionId) {
    throw new Error('Cashfree payment session could not be generated by the backend.');
  }

  return data;
}
